Workaround remaining issue loading react/jsx-runtime
This release fixes the previous issue with `useCodeMirror`
introduced in 4.23.11 but leaves a related issue loading
`react/jsx-runtime`

```
Error: Cannot find module 'node_modules/react/jsx-runtime' imported from node_modules/@uiw/react-codemirror/esm/index.js
Did you mean to import "react/jsx-runtime.js"?
```

Update the Vitest config to process the CodeMirror dependency
to workaround this.

From the Vitest docs:
> Vite will process inlined modules. This could be helpful to handle
> packages that ship .js in ESM format (that Node can't handle).