Reduce noise in unit test logs
The logs contain a number of the following type of error:
```
      Error: Not implemented: window.computedStyle(elt, pseudoElt)
          at module.exports
(/home/prow/go/src/github.com/tektoncd/dashboard/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
          at Window.getComputedStyle
(/home/prow/go/src/github.com/tektoncd/dashboard/node_modules/jsdom/lib/jsdom/browser/Window.js:798:7)
          at getComputedStyle
(/home/prow/go/src/github.com/tektoncd/dashboard/node_modules/carbon-components-react/lib/components/Tooltip/Tooltip.js:81:55)
```

This is caused by the Carbon Tooltip component passing a second argument to
`getComputedStyle` referencing a pseudo element. This is not implemented in
jsdom resulting in the errors.

Since this shouldn't affect the tests, strip the second argument when calling
`getComputedStyle` in the tests to resolve the error and reduce noise in the logs.